
# Vypíše názvy všetkých sladkostí ktoré neobsahujú VejceAlergen zoradených podľa hmotnosti
SELECT ?nazev
WHERE {
  ?sladkost a ex:Sladkost.
  ?sladkost ex:hmotnost ?hmotnost.
  ?sladkost ex:názevSladkosti ?nazev.
  FILTER NOT EXISTS {
   ?sladkost ex:obsahujeSurovinu/ex:obsahujeAlergen ex:VejceAlergen. 
  }
} ORDER BY ASC(?hmotnost)